# Use a lean base image for Python 3.11
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# 1. Copy requirements and install dependencies
# We install dependencies first to leverage Docker's caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copy the entire source code folder
# This includes rag_api.py, ingestion_service.py, and sec_edgar_client.py
COPY src/ /app/src/

# 3. CRITICAL STEP: Copy the large, pre-built vector database
# This directory contains all the chunks and embeddings generated by ingestion_service.py
# Make sure you run ingestion_service.py BEFORE building the Docker image!
COPY chroma_db/ /app/chroma_db/

# 4. Copy the startup script
COPY run_api.sh .

# 5. Expose the port where the Flask application will run
EXPOSE 5000

# 6. Set the entrypoint to run the startup script
CMD ["sh", "run_api.sh"]
